### ISSUE TITLE
Standalone version ?

### ISSUE THREAD

**Issue by beppe9000** [ediamin/wp-console#3]
I was wondering if it's possible to decouple this from Wordpress and use it standalone like https://repl.it

**Comment by ediamin** [comment]
Hi @beppe9000! Yes it is possible to decouple the web console from WordPress, but unfortunately, I have to plan to make one in near future.  The code is open source and free to use/abuse. So, if you have time and patience you can make one yourself. Good luck!

**Comment by beppe9000** [comment]
Could you write a brief summary for someone who is not familiar with the codebase on what to change ?
